// Complete LanguageTool language catalog for Lexicon.
// All codes map strictly to LanguageTool v6.8 Java engine short codes & country variants.
// English variants are pinned at the top; all other languages are sorted strictly alphabetically.

export const LANGUAGES = [
  // ── English Variants (Pinned Top) ──
  { code: "en-US", name: "English (US)", label: "English (United States)" },
  { code: "en-GB", name: "English (UK)", label: "English (United Kingdom)" },
  { code: "en-AU", name: "English (Australia)", label: "English (Australia)" },
  { code: "en-CA", name: "English (Canada)", label: "English (Canada)" },
  { code: "en-NZ", name: "English (New Zealand)", label: "English (New Zealand)" },
  { code: "en-ZA", name: "English (South Africa)", label: "English (South Africa)" },

  // ── Alphabetical Global Languages ──
  { code: "ar", name: "Arabic", label: "Arabic" },
  { code: "ast", name: "Asturian (Spain)", label: "Asturian (Spain)" },
  { code: "be", name: "Belarusian (Belarus)", label: "Belarusian (Belarus)" },
  { code: "br", name: "Breton (France)", label: "Breton (France)" },
  { code: "ca-ES-balear", name: "Catalan (Balearic)", label: "Catalan (Balearic)" },
  { code: "ca", name: "Catalan (Spain)", label: "Catalan (Spain)" },
  { code: "ca-ES-valencia", name: "Catalan (Valencian)", label: "Catalan (Valencian)" },
  { code: "zh-CN", name: "Chinese (Simplified)", label: "Chinese (Simplified)" },
  { code: "crh", name: "Crimean Tatar (Ukraine)", label: "Crimean Tatar (Ukraine)" },
  { code: "da", name: "Danish (Denmark)", label: "Danish (Denmark)" },
  { code: "nl-BE", name: "Dutch (Belgium)", label: "Dutch (Belgium)" },
  { code: "nl", name: "Dutch (Netherlands)", label: "Dutch (Netherlands)" },
  { code: "eo", name: "Esperanto", label: "Esperanto" },
  { code: "fr-BE", name: "French (Belgium)", label: "French (Belgium)" },
  { code: "fr-CA", name: "French (Canada)", label: "French (Canada)" },
  { code: "fr", name: "French (France)", label: "French (France)" },
  { code: "fr-CH", name: "French (Switzerland)", label: "French (Switzerland)" },
  { code: "gl", name: "Galician (Spain)", label: "Galician (Spain)" },
  { code: "de-AT", name: "German (Austria)", label: "German (Austria)" },
  { code: "de-DE", name: "German (Germany)", label: "German (Germany)" },
  { code: "de-CH", name: "German (Swiss)", label: "German (Swiss)" },
  { code: "el", name: "Greek (Greece)", label: "Greek (Greece)" },
  { code: "ga", name: "Irish (Ireland)", label: "Irish (Ireland)" },
  { code: "it", name: "Italian (Italy)", label: "Italian (Italy)" },
  { code: "ja", name: "Japanese (Japan)", label: "Japanese (Japan)" },
  { code: "km", name: "Khmer (Cambodia)", label: "Khmer (Cambodia)" },
  { code: "fa", name: "Persian (Iran)", label: "Persian / Farsi (Iran)" },
  { code: "pl", name: "Polish (Poland)", label: "Polish (Poland)" },
  { code: "pt-AO", name: "Portuguese (Angola preAO)", label: "Portuguese (Angola preAO)" },
  { code: "pt-BR", name: "Portuguese (Brazil)", label: "Portuguese (Brazil)" },
  { code: "pt-MZ", name: "Portuguese (Moçambique preAO)", label: "Portuguese (Moçambique preAO)" },
  { code: "pt-PT", name: "Portuguese (Portugal)", label: "Portuguese (Portugal)" },
  { code: "ro", name: "Romanian (Romania)", label: "Romanian (Romania)" },
  { code: "ru", name: "Russian (Russia)", label: "Russian (Russia)" },
  { code: "de-DE-x-simple-language", name: "Simple German", label: "Simple German" },
  { code: "sk", name: "Slovak (Slovakia)", label: "Slovak (Slovakia)" },
  { code: "sl", name: "Slovenian (Slovenia)", label: "Slovenian (Slovenia)" },
  { code: "es", name: "Spanish (Spain)", label: "Spanish (Spain)" },
  { code: "es-AR", name: "Spanish (voseo)", label: "Spanish (voseo)" },
  { code: "sv", name: "Swedish (Sweden)", label: "Swedish (Sweden)" },
  { code: "tl", name: "Tagalog (Philippines)", label: "Tagalog (Philippines)" },
  { code: "ta", name: "Tamil (India)", label: "Tamil (India)" },
  { code: "uk", name: "Ukrainian (Ukraine)", label: "Ukrainian (Ukraine)" },
];
